NorthWind/Models/Shipper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NorthWind.Models
{
    public class Shipper
    {
        
        public int ShipperId { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }

    }
}

NorthWind/Controllers/ShippersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NorthWind.Models;
using Northwind.DAL;

namespace NorthWind.Controllers
{
    public class ShippersController : Controller
    {
        private NorthwindContext db = new NorthwindContext();

        // GET: Shippers
        public ActionResult Index()
        {
            return View(db.Shippers.ToList());
        }

        // GET: Shippers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shipper shipper = db.Shippers.Find(id);
            if (shipper == null)
            {
                return HttpNotFound();
            }
            return View(shipper);
        }

        // GET: Shippers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shippers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShipperId,CompanyName,Phone")] Shipper shipper)
        {
            if (ModelState.IsValid)
            {
                db.Shippers.Add(shipper);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(shipper);
        }

        // GET: Shippers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shipper shipper = db.Shippers.Find(id);
            if (shipper == null)
            {
                return HttpNotFound();
            }
            return View(shipper);
        }

        // POST: Shippers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShipperId,CompanyName,Phone")] Shipper shipper)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shipper).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(shipper);
        }

        // GET: Shippers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shipper shipper = db.Shippers.Find(id);
            if (shipper == null)
            {
                return HttpNotFound();
            }
            return View(shipper);
        }

        // POST: Shippers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Shipper shipper = db.Shippers.Find(id);
            db.Shippers.Remove(shipper);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NorthWind/Views/Shippers/Create.cshtml
@model NorthWind.Models.Shipper

@{
    ViewBag.Title = "Create";
}



<div class="row">
    <div class="col-lg-4 col-sm-1"></div>
    <div class="col-lg-4 col-sm-10">

        <h2>Create</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()


            <div class="form-horizontal">
                <h4>Shipper</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-12">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
        <br />
        <div>
           
            <a href='@Url.Action("Index","Shippers")'><span class="glyphicon glyphicon-chevron-left"></span> Back to List</a>
        </div>

    </div>
    <div class="col-lg-4 col-sm-1"></div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NorthWind/Views/Shippers/Delete.cshtml
@model NorthWind.Models.Shipper

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shipper</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NorthWind/Views/Shippers/Details.cshtml
@model NorthWind.Models.Shipper

@{
    ViewBag.Title = "Details";
}



<div class="container">
    <div class="row">
        <div class="col-lg-4 col-sm-1"></div>
        <div class="col-lg-4 col-sm-10">
            <h2>Details</h2>
            <h4>Shipper</h4>
            <hr />
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-bordered">
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.CompanyName)</td>
                            <td>@Html.DisplayFor(model => model.CompanyName)</td>
                        </tr>

                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Phone)</td>
                            <td>@Html.DisplayFor(model => model.Phone)</td>
                        </tr>




                    </table>
                    </div>
                </div>

                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.ShipperId }, new { @class = "btn btn-primary" }) <br /><br />

                    <a href='@Url.Action("Index","Shippers")'><span class="glyphicon glyphicon-chevron-left"></span> Back to List</a>
                </p>
            </div>
            <div class="col-lg-4 col-sm-1"></div>
        </div>
    
</div>

NorthWind/Views/Shippers/Edit.cshtml
@model NorthWind.Models.Shipper

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shipper</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShipperId)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NorthWind/Views/Shippers/Index.cshtml
@model IEnumerable<NorthWind.Models.Shipper>

@{
    ViewBag.Title = "Index";
}

<h2>All Shippers</h2>

<p style="text-align:right">
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
</p>
<table  class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
           

            @Html.ActionLink("Details", "Details", new { id = item.ShipperId }, new { @class = "btn btn-primary" }) | 
            <a href="@Url.Action("Edit", "Shippers", new { id = item.ShipperId })" style="color:cornflowerblue"><span class="glyphicon glyphicon-pencil"></span></a>
            |
            <a href="@Url.Action("Delete", "Shippers", new { id = item.ShipperId })" style="color:grey"><span class="glyphicon glyphicon-trash"></span></a>
        </td>
    </tr>
}

</table>